### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by MichaelDeBoey** [JonnyBnator/remix-auth-discord#1]
It seems like `remix-auth-discord` isn't published on npm.

https://www.npmjs.com/package/remix-auth-discord

**Comment by MichaelDeBoey** [comment]
@JonnyBnator Is there something I can help out with to get this package published on npm?

**Comment by JonnyBnator** [comment]
@MichaelDeBoey Sorry I had been very busy and missed this issue. I will look into publishing it soon, should I need assistance, I will let you know. Thanks for the offer :)

**Comment by JonnyBnator** [comment]
@MichaelDeBoey it is now published on npm. :)
