### ISSUE TITLE
Response not returning the guilds the user authenticated is in

### ISSUE THREAD

**Issue by Xolo-Gamerz** [JonnyBnator/remix-auth-discord#2]
How do i get the info about all the guilds the user authenticated. The raw data doesn't provide the information about the user guilds even if the guilds scope has been used.

**Comment by JonnyBnator** [comment]
The original authentication method does not return guilds.

If you use the "guilds" scope that only allows your application to query the user guilds with the given access token.
To actually retrieve the guilds of the user, you need to make an api call to discord with the access token.
https://discord.com/developers/docs/resources/user#get-current-user-guilds

**Comment by Xolo-Gamerz** [comment]
Thank you that resolved my issue, though it would have been more convenient if it would have been inbuilt.

**Comment by JonnyBnator** [comment]
Thanks for the suggestion. I will make include an example to fetch the guilds as well. That sounds like a good solution to me :)
