### ISSUE TITLE
Cookie length will exceed browser maximum

### ISSUE THREAD

**Issue by xhyrom** [JonnyBnator/remix-auth-discord#4]
When i try to login, it throws:
```
Unexpected Server Error

Error: Cookie length will exceed browser maximum. Length: 10387
```

when i remove guilds from object it works but i need guilds

**Comment by JonnyBnator** [comment]
In the example it explicitly says that this is likey to happen and what to do in that case.
Here it is again:

>   IMPORTANT: This can quickly fill the session storage to be too big.
     So make sure you only return the values from the guilds (and the guilds) you actually need
     (eg. omit the features)
     and if that's still to big, you need to store the guilds some other way. (Your own DB)

**Comment by xhyrom** [comment]
ah yeh, sorry
