### ISSUE TITLE
Url is wrong encoded

### ISSUE THREAD

**Issue by Tomato6966** [JonnyBnator/remix-auth-discord#5]
https://discord.com/api/v10/oauth2/authorize?scope=identify%2Cguilds%2Cguilds.members.read&prompt?.....

as you can see it does identify%2Cguilds... it should be identify%20guilds

**Comment by Tomato6966** [comment]
![image](https://github.com/JonnyBnator/remix-auth-discord/assets/68145571/8417eca6-35fb-49a8-b768-6b79eb142979)
![image](https://github.com/JonnyBnator/remix-auth-discord/assets/68145571/60ea78d0-1ebb-4719-8050-1f8a1a95cd0d)
![image](https://github.com/JonnyBnator/remix-auth-discord/assets/68145571/6807700f-2a92-4084-a5d2-ab060866a119)

here are some debugging things

**Comment by Tomato6966** [comment]
I'm on node v20.7.0

**Comment by Tomato6966** [comment]
The fault is in remix-auth-oauth2 in getAuthorizationUrl
![image](https://github.com/JonnyBnator/remix-auth-discord/assets/68145571/4c4f5f10-c4df-492b-a28a-1fa8b5995000)
![image](https://github.com/JonnyBnator/remix-auth-discord/assets/68145571/78963bbc-9f74-47e2-9ccb-8a3693adccfa)

**Comment by Tomato6966** [comment]
params.set("scope", Array.isArray(this.scope) ? this.scope.join(" ") : this.scope);

that would fix it (in remix-auth-oauth2)

this.scope has to be a STRING not an array.

**Comment by Tomato6966** [comment]
https://github.com/JonnyBnator/remix-auth-discord/pull/6

Issue is probably because remix-auth-oauth2 now sets the params for scope's too. but requires this.scope to be a string.

2 Solutions:
set this.scope to string not array

rename this.scope to this._scope and then it won't adjust it since you override the class

I made a PR for solution 1 which seems to work for me

**Comment by JonnyBnator** [comment]
Resolved with PR #6
