### ISSUE TITLE
Example strategy instance has type errors

### ISSUE THREAD

**Issue by uerkw** [JonnyBnator/remix-auth-discord#8]
Using the provided strategy example, there are some errors in the file
`app/auth.server.ts`

Using a new remix project on Vite (remix ^2.8.1, remix-auth-discord ^1.3.2), I encountered type errors related to the `DiscordPartialGuild` and omitting the `features` field, which carries extra data. This field is required in the exported type used, and causes some unsightly errors

A work around was as follows, by defining new types that do not require this field when omitting from Discord Guild information.

```
export interface CustomDiscordGuild {
    id: string;
    name: string;
    icon: string | null;
    owner: boolean;
    permissions: string;
}
```

Then in the interface `DiscordUser`, change
`guilds?: Array<PartialDiscordGuild>` to
`guilds?: Array<CustomDiscordGuild>`

This will omit the `features` of a Discord guild without running into issues with the library.

Theoretically, there should be an extra type or optional indicator on the `features` type in `DiscordPartialGuild` to allow optionally submitting the information to the Authenticator through the strategy.

Finally, there is one type error with `locale` on the return object, as `locale` is not found on the `DiscordUser` interface defined above. Is this data needed and can it be safely ignored?

I'd be happy to provide my working `auth.server.ts` file for what got things "working" for me in a new Vite/Remix project.

**Comment by JonnyBnator** [comment]
Thank you for raising this issue.

The `PartialDiscordGuild` type reflects the way guilds are received from the Discord API. This includes the features.
The correct way to handle this type for your use case is to extend/omit certain fields from it in your own implementation of the type.
So basically just the way you already did it.
Actually I already had it setup that way in my testing environment, apparently i forgot to update the public example though. This is now fixed :)

For the `DiscordLocale` type, same problem, it was in my testing environment, but not included in the public example. This should now also be fixed.
And to answer your question if you need it or can safely ignore it - that depends on you. You could display your application in the selected locale for the User, then you would need it.
